<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'projectName' => array( 'totalsType' => '' ),
'projectStart' => array( 'totalsType' => '' ),
'projectEnd' => array( 'totalsType' => '' ),
'researchFundingType' => array( 'totalsType' => '' ),
'contactName' => array( 'totalsType' => '' ),
'approveStatus' => array( 'totalsType' => '' ),
'approveDate' => array( 'totalsType' => '' ),
'DocumentCheckStatus' => array( 'totalsType' => '' ),
'projectBudgetCost' => array( 'totalsType' => '' ),
'disbureAmounts' => array( 'totalsType' => '' ),
'projectFile' => array( 'totalsType' => '' ),
'entryUserName' => array( 'totalsType' => '' ),
'entryTime' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'projectName',
'projectStart',
'projectEnd',
'researchFundingType',
'contactName',
'projectBudgetCost',
'entryUserName',
'entryTime',
'disbureAmounts' ),
'exportFields' => array( 'projectName',
'contactName',
'projectStart',
'projectEnd',
'researchFundingType',
'projectBudgetCost',
'entryUserName',
'entryTime',
'disbureAmounts' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'projectName' => array( 'export_field1' ),
'projectStart' => array( 'export_field2' ),
'projectEnd' => array( 'export_field3' ),
'researchFundingType' => array( 'export_field4' ),
'contactName' => array( 'export_field5' ),
'projectBudgetCost' => array( 'export_field9' ),
'entryUserName' => array( 'export_field12' ),
'entryTime' => array( 'export_field13' ),
'disbureAmounts' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field5',
'export_field2',
'export_field3',
'export_field4',
'export_field9',
'export_field12',
'export_field13',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field5' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field9' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field9',
'export_field12',
'export_field13',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field5',
'export_field2',
'export_field3',
'export_field4',
'export_field9',
'export_field12',
'export_field13',
'export_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'projectName',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'projectStart',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'projectEnd',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'researchFundingType',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'contactName',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'projectBudgetCost',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'entryUserName',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'entryTime',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'disbureAmounts',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 7,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>