<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'fields' => array( 'gridFields' => array( 'progressStep',
'progressDate',
'trackDesc',
'trackAttFille',
'entryUserName',
'entryTime',
'approveDate',
'approveStatus',
'approveReason',
'contactName',
'progressStatus',
'progressReason' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'entryTime',
'progressReason',
'progressStatus',
'progressDate',
'contactName',
'approveReason',
'approveStatus',
'approveDate',
'trackDate',
'trackDesc',
'trackAttFille',
'projectID',
'progressStep',
'id',
'entryUserName' ),
'filterFields' => array(  ),
'fieldItems' => array( 'progressStep' => array( 'report_grid_field3' ),
'progressDate' => array( 'report_grid_field4' ),
'trackDesc' => array( 'report_grid_field5' ),
'trackAttFille' => array( 'report_grid_field6' ),
'entryUserName' => array( 'report_grid_field7' ),
'entryTime' => array( 'report_grid_field8' ),
'projectID' => array( 'report_group_field' ),
'trackDate' => array( 'report_group_field1' ),
'approveDate' => array( 'report_grid_field' ),
'approveStatus' => array( 'report_grid_field1' ),
'approveReason' => array( 'report_grid_field2' ),
'contactName' => array( 'report_grid_field9' ),
'progressStatus' => array( 'report_grid_field10' ),
'progressReason' => array( 'report_grid_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel' ),
'top' => array( 'breadcrumb' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_grid_field3',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field9',
'report_grid_field4',
'report_grid_field10',
'report_grid_field11' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'grpsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'breadcrumb' ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'breadcrumb' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'print_panel' => 5,
'menu' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'search_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'-' => array( '-',
'-1',
'-2' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'lang_selector' => array( 'lang_selector' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'advsearch_link' => array( 'advsearch_link' ),
'report_grid_field' => array( 'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'report',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'D8C1BF',
'summary' => 'FFE4E1' ),
'field' => 'projectID' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '9DACBB',
'summary' => 'B9CBDD' ),
'field' => 'trackDate' ) ),
'fields' => array( array( 'avg' => false,
'field' => 'progressStep',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackDesc',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackAttFille',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryUserName',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryTime',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'approveDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'contactName',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'stepped',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field3',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field9',
'report_grid_field4',
'report_grid_field10',
'report_grid_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'D8C1BF',
'summary' => 'FFE4E1' ),
'field' => 'projectID' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '9DACBB',
'summary' => 'B9CBDD' ),
'field' => 'trackDate' ) ),
'fields' => array( array( 'avg' => false,
'field' => 'progressStep',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackDesc',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackAttFille',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryUserName',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryTime',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'approveDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'contactName',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'stepped',
'vertSummary' => false ) ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-2',
'export_report_excel',
'export_report_word',
'-1',
'lang_selector' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field14',
'search_panel_field13',
'search_panel_field8',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field5',
'search_panel_field7',
'search_panel_field6',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'-' => array( 'type' => '-' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'entryTime',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'entryUserName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'id',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'progressStep',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'projectID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field5' => array( 'field' => 'trackDate',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'trackAttFille',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'trackDesc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'progressDate',
'type' => 'search_panel_field',
'required' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'lang_selector' => array( 'type' => 'lang_selector' ),
'-1' => array( 'type' => '-' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'report_grid_field3' => array( 'field' => 'progressStep',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field4' => array( 'field' => 'progressDate',
'type' => 'report_grid_field' ),
'report_grid_field5' => array( 'field' => 'trackDesc',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field6' => array( 'field' => 'trackAttFille',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field7' => array( 'field' => 'entryUserName',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field8' => array( 'field' => 'entryTime',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field' => array( 'field' => 'projectID',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'trackDate',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_grid_field' => array( 'field' => 'approveDate',
'type' => 'report_grid_field' ),
'search_panel_field9' => array( 'field' => 'approveDate',
'type' => 'search_panel_field',
'required' => false ),
'report_grid_field1' => array( 'field' => 'approveStatus',
'type' => 'report_grid_field' ),
'search_panel_field10' => array( 'field' => 'approveStatus',
'type' => 'search_panel_field',
'required' => false ),
'report_grid_field2' => array( 'field' => 'approveReason',
'type' => 'report_grid_field' ),
'search_panel_field11' => array( 'field' => 'approveReason',
'type' => 'search_panel_field',
'required' => false ),
'report_grid_field9' => array( 'field' => 'contactName',
'type' => 'report_grid_field' ),
'search_panel_field12' => array( 'field' => 'contactName',
'type' => 'search_panel_field',
'required' => false ),
'report_grid_field10' => array( 'field' => 'progressStatus',
'type' => 'report_grid_field' ),
'search_panel_field13' => array( 'field' => 'progressStatus',
'type' => 'search_panel_field',
'required' => false ),
'report_grid_field11' => array( 'field' => 'progressReason',
'type' => 'report_grid_field' ),
'search_panel_field14' => array( 'field' => 'progressReason',
'type' => 'search_panel_field',
'required' => false ) ),
'dbProps' => array(  ),
'version' => 7,
'pageWidth' => 'full' );
		?>