<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'progressStep',
'progressDate',
'trackDesc',
'trackAttFille',
'entryUserName',
'entryTime',
'approveDate',
'approveStatus',
'approveReason',
'contactName',
'progressStatus',
'progressReason' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'progressStep' => array( 'report_grid_field3' ),
'progressDate' => array( 'report_grid_field4' ),
'trackDesc' => array( 'report_grid_field5' ),
'trackAttFille' => array( 'report_grid_field6' ),
'entryUserName' => array( 'report_grid_field7' ),
'entryTime' => array( 'report_grid_field8' ),
'projectID' => array( 'report_group_field' ),
'trackDate' => array( 'report_group_field1' ),
'approveDate' => array( 'report_grid_field' ),
'approveStatus' => array( 'report_grid_field1' ),
'approveReason' => array( 'report_grid_field2' ),
'contactName' => array( 'report_grid_field9' ),
'progressStatus' => array( 'report_grid_field10' ),
'progressReason' => array( 'report_grid_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_grid_field3',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field9',
'report_grid_field4',
'report_grid_field10',
'report_grid_field11' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'D8C1BF',
'summary' => 'FFE4E1' ),
'field' => 'projectID' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '9DACBB',
'summary' => 'B9CBDD' ),
'field' => 'trackDate' ) ),
'fields' => array( array( 'avg' => false,
'field' => 'progressStep',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackDesc',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackAttFille',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryUserName',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryTime',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'approveDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'contactName',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'stepped',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field3',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field9',
'report_grid_field4',
'report_grid_field10',
'report_grid_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'D8C1BF',
'summary' => 'FFE4E1' ),
'field' => 'projectID' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '9DACBB',
'summary' => 'B9CBDD' ),
'field' => 'trackDate' ) ),
'fields' => array( array( 'avg' => false,
'field' => 'progressStep',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackDesc',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'trackAttFille',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryUserName',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'entryTime',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'approveDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'approveReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'contactName',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressDate',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressStatus',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'progressReason',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'stepped',
'vertSummary' => false ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field3' => array( 'field' => 'progressStep',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field4' => array( 'field' => 'progressDate',
'type' => 'report_grid_field' ),
'report_grid_field5' => array( 'field' => 'trackDesc',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field6' => array( 'field' => 'trackAttFille',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field7' => array( 'field' => 'entryUserName',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field8' => array( 'field' => 'entryTime',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field' => array( 'field' => 'projectID',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'trackDate',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_grid_field' => array( 'field' => 'approveDate',
'type' => 'report_grid_field' ),
'report_grid_field1' => array( 'field' => 'approveStatus',
'type' => 'report_grid_field' ),
'report_grid_field2' => array( 'field' => 'approveReason',
'type' => 'report_grid_field' ),
'report_grid_field9' => array( 'field' => 'contactName',
'type' => 'report_grid_field' ),
'report_grid_field10' => array( 'field' => 'progressStatus',
'type' => 'report_grid_field' ),
'report_grid_field11' => array( 'field' => 'progressReason',
'type' => 'report_grid_field' ) ),
'dbProps' => array(  ),
'version' => 7,
'pageWidth' => 'full' );
		?>