<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'projectID' => array( 'totalsType' => '' ),
'trackDate' => array( 'totalsType' => '' ),
'progressStep' => array( 'totalsType' => '' ),
'trackDesc' => array( 'totalsType' => '' ),
'trackAttFille' => array( 'totalsType' => '' ),
'contactName' => array( 'totalsType' => '' ),
'progressDate' => array( 'totalsType' => '' ),
'progressStatus' => array( 'totalsType' => '' ),
'progressReason' => array( 'totalsType' => '' ),
'approveDate' => array( 'totalsType' => '' ),
'approveStatus' => array( 'totalsType' => '' ),
'approveReason' => array( 'totalsType' => '' ),
'entryUserName' => array( 'totalsType' => '' ),
'entryTime' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'entryUserName',
'entryTime',
'progressStep',
'progressDate',
'trackDesc',
'trackAttFille',
'projectID',
'trackDate',
'approveDate',
'approveStatus',
'approveReason',
'progressStatus',
'progressReason',
'contactName' ),
'exportFields' => array( 'projectID',
'trackDate',
'contactName',
'progressStep',
'trackDesc',
'trackAttFille',
'progressDate',
'progressStatus',
'progressReason',
'approveDate',
'approveStatus',
'approveReason',
'entryUserName',
'entryTime' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'entryUserName' => array( 'export_field9' ),
'entryTime' => array( 'export_field10' ),
'progressStep' => array( 'export_field' ),
'progressDate' => array( 'export_field2' ),
'trackDesc' => array( 'export_field3' ),
'trackAttFille' => array( 'export_field4' ),
'projectID' => array( 'export_field5' ),
'trackDate' => array( 'export_field1' ),
'approveDate' => array( 'export_field6' ),
'approveStatus' => array( 'export_field7' ),
'approveReason' => array( 'export_field8' ),
'progressStatus' => array( 'export_field11' ),
'progressReason' => array( 'export_field12' ),
'contactName' => array( 'export_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field5',
'export_field1',
'export_field13',
'export_field',
'export_field3',
'export_field4',
'export_field2',
'export_field11',
'export_field12',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field5' => 'grid',
'export_field1' => 'grid',
'export_field13' => 'grid',
'export_field' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field2' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field9',
'export_field10',
'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field1',
'export_field6',
'export_field7',
'export_field8',
'export_field11',
'export_field12',
'export_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field5',
'export_field1',
'export_field13',
'export_field',
'export_field3',
'export_field4',
'export_field2',
'export_field11',
'export_field12',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field9' => array( 'field' => 'entryUserName',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'entryTime',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'progressStep',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'progressDate',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'trackDesc',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'trackAttFille',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'projectID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'trackDate',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'approveDate',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'approveStatus',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'approveReason',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'progressStatus',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'progressReason',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'contactName',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 7,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>