<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_project  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowEdit"]=true;


		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		
	if ($_SESSION["GroupName"]=="เจ้าหน้าที่") {

		$pageObject->hideField("approveStatus");
		$pageObject->hideField("approveDate");
		$pageObject->hideField("approveReason");
		$pageObject->hideField("screenDate");
		$pageObject->hideField("screenStatus");
		$pageObject->hideField("screenReason");
	}
	elseif ($_SESSION["GroupName"]=="คณะกลั่นกรอง") {

		$pageObject->hideField("DocumentCheckStatus");
		$pageObject->hideField("DocumentCheckDate");
		$pageObject->hideField("DocumentCheckReason");
		$pageObject->hideField("approveStatus");
		$pageObject->hideField("approveDate");
		$pageObject->hideField("approveReason");

	}
	elseif ($_SESSION["GroupName"]=="คณะกรรมการ") {

		$pageObject->hideField("DocumentCheckStatus");
		$pageObject->hideField("DocumentCheckDate");
		$pageObject->hideField("DocumentCheckReason");
		$pageObject->hideField("screenDate");
		$pageObject->hideField("screenStatus");
		$pageObject->hideField("screenReason");
	}
	elseif ($_SESSION["GroupName"]=="คณะกรรมการบริหารโครงการ") {

		$pageObject->hideField("DocumentCheckStatus");
		$pageObject->hideField("DocumentCheckDate");
		$pageObject->hideField("DocumentCheckReason");
		$pageObject->hideField("screenDate");
		$pageObject->hideField("screenStatus");
		$pageObject->hideField("screenReason");
		$pageObject->hideField("approveStatus");
		$pageObject->hideField("approveDate");
		$pageObject->hideField("approveReason");
	}
	elseif ($_SESSION["GroupName"]=="ปลัดฯ") {

		$pageObject->hideField("DocumentCheckStatus");
		$pageObject->hideField("DocumentCheckDate");
		$pageObject->hideField("DocumentCheckReason");
		$pageObject->hideField("screenDate");
		$pageObject->hideField("screenStatus");
		$pageObject->hideField("screenReason");
		$pageObject->hideField("approveStatus");
		$pageObject->hideField("approveDate");
		$pageObject->hideField("approveReason");
	}
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		

		Mail2ProjectAlert($_SESSION["MailSettings"],$values);
	

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		
		Mail2ProjectAlert($_SESSION["MailSettings"],$values);

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		
		$values["DocumentCheckStatus"] = "รอตรวจสอบ";
		$values["screenStatus"] = "รอตรวจสอบ";
		$values["approveStatus"] = "รออนุมัติ";

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
