<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tasktrack  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["BeforeShowEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		
		$values["progressStatus"] = "รอตรวจสอบ";
		$values["approveStatus"] = "รออนุมัติ";


// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		
	if ($_SESSION["GroupName"]=="เจ้าหน้าที่") {

		$pageObject->hideField("approveStatus");
		$pageObject->hideField("approveDate");
		$pageObject->hideField("approveReason");

	}
	elseif (($_SESSION["GroupName"]=="คณะกลั่นกรอง") OR ($_SESSION["GroupName"]=="คณะกรรมการ") OR  ($_SESSION["GroupName"]=="ปลัดฯ")){

		$pageObject->hideField("progressStatus");
		$pageObject->hideField("progressDate");
		$pageObject->hideField("progressReason");
		$pageObject->hideField("approveStatus");
		$pageObject->hideField("approveDate");
		$pageObject->hideField("approveReason");

	}
	elseif ($_SESSION["GroupName"]=="คณะกรรมการบริหารโครงการ") {

		$pageObject->hideField("progressStatus");
		$pageObject->hideField("progressDate");
		$pageObject->hideField("progressReason");
	}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
